Vagrant.configure("2") do |config|
    config.vm.box = "debian-sandbox/bookworm64"
    config.vm.network "private_network", type: "dhcp"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "docker_install.yml"
    end
  end
  